name: flame_tiled_utils
description: A set of useful utils to extend tiled functionality, such as processing each tile
  individually, easy loading tile's sprite or animation, compositing tiles into single image
version: 1.2.0
homepage: https://github.com/ASGAlex/flame_tiled_utils
repository: https://github.com/ASGAlex/flame_tiled_utils

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flame: ^1.17.0
  flame_tiled: ^1.10.2
  tiled: any
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
