name: flame_tiled_utils
description: A set of useful utils to extend tiled functionality
version: 1.0.0
homepage: https://github.com/ASGAlex/flame_tiled_utils

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flame: ^1.2.1
  flame_tiled: ^1.6.0
  tiled: 0.8.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
